https://pytorch.org/tutorials/beginner/basics/buildmodel_tutorial.html

In [1]:
import torch
from torch import nn

In [3]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [4]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Using {} device'.format(device))

Using cuda device


In [5]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten()
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [10]:
X = torch.rand(1, 28, 28, device=device)
X

tensor([[[4.0107e-01, 1.6524e-01, 8.5029e-01, 2.1274e-01, 6.3077e-01,
          8.8386e-01, 6.5324e-01, 6.1185e-01, 2.3237e-01, 7.9395e-01,
          4.7899e-02, 8.5907e-01, 2.9867e-01, 8.1223e-01, 2.2499e-01,
          1.3539e-01, 7.0724e-01, 5.3095e-01, 8.5132e-01, 4.2947e-01,
          8.5333e-01, 7.2603e-02, 4.8446e-01, 3.0369e-01, 7.2293e-01,
          8.6056e-01, 7.2783e-01, 8.6004e-04],
         [8.7178e-01, 2.0585e-01, 3.5467e-01, 6.6485e-01, 6.4393e-01,
          2.4276e-02, 5.8983e-01, 2.4818e-01, 7.7257e-01, 3.5956e-01,
          7.0484e-01, 5.8190e-01, 6.3531e-01, 6.3390e-01, 7.2670e-01,
          9.2514e-01, 7.2127e-01, 8.2472e-01, 4.3066e-01, 7.3061e-01,
          9.0026e-01, 5.7986e-01, 4.9032e-01, 7.1654e-01, 6.5162e-01,
          5.7642e-01, 9.3393e-01, 9.0961e-01],
         [3.9701e-01, 4.1536e-01, 3.4440e-01, 2.4660e-01, 1.1120e-01,
          7.5939e-01, 1.7776e-01, 3.5728e-01, 9.3402e-01, 1.8807e-02,
          6.7759e-01, 5.9238e-01, 3.3983e-01, 7.9594e-02, 9.0730e-

In [11]:
logits = model(X)
logits

tensor([[ 0.0168, -0.0145,  0.0108, -0.0308, -0.0248,  0.1108, -0.0258,  0.0318,
         -0.0387, -0.0164]], device='cuda:0', grad_fn=<AddmmBackward>)

In [12]:
pred_probab = nn.Softmax(dim=1)(logits)
pred_probab

tensor([[0.1014, 0.0983, 0.1008, 0.0967, 0.0973, 0.1114, 0.0972, 0.1029, 0.0959,
         0.0981]], device='cuda:0', grad_fn=<SoftmaxBackward>)

In [13]:
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

Predicted class: tensor([5], device='cuda:0')


In [14]:
input_image = torch.rand(3,28,28)
print(input_image.size())

torch.Size([3, 28, 28])


In [15]:
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


In [16]:
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


In [17]:
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

Before ReLU: tensor([[-0.2282, -0.0438,  0.6194, -0.4067,  0.6907,  0.2030,  0.3688,  0.3396,
         -0.6019, -0.4045,  0.1409,  0.2198, -0.0515,  0.0283, -0.3722, -0.1736,
          0.1188, -0.2527, -0.3131,  0.0231],
        [ 0.0561,  0.4880,  0.6106,  0.1094,  0.6957,  0.4406,  0.2356,  0.2651,
         -0.4235, -0.6626,  0.3244,  0.0231,  0.2321, -0.0122, -0.4175,  0.1186,
          0.1872, -0.5331, -0.3216,  0.2493],
        [-0.0596,  0.3645,  0.6605, -0.0875,  0.2718,  0.0917,  0.0350,  0.2355,
         -0.1490, -0.5715,  0.0413,  0.0921,  0.1937,  0.2270, -0.1556, -0.1567,
         -0.0662, -0.2231, -0.5896, -0.0056]], grad_fn=<AddmmBackward>)


After ReLU: tensor([[0.0000, 0.0000, 0.6194, 0.0000, 0.6907, 0.2030, 0.3688, 0.3396, 0.0000,
         0.0000, 0.1409, 0.2198, 0.0000, 0.0283, 0.0000, 0.0000, 0.1188, 0.0000,
         0.0000, 0.0231],
        [0.0561, 0.4880, 0.6106, 0.1094, 0.6957, 0.4406, 0.2356, 0.2651, 0.0000,
         0.0000, 0.3244, 0.0231, 0.2321, 0.0000, 0.000

In [19]:
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)
input_image = torch.rand(3,28,28)
logits = seq_modules(input_image)
logits

tensor([[-0.1758,  0.4133,  0.2703,  0.3293,  0.0935, -0.1985, -0.1184,  0.3020,
         -0.1306,  0.1350],
        [-0.1598,  0.5280,  0.2524,  0.3452,  0.1110, -0.2142, -0.1057,  0.3620,
         -0.1912,  0.2405],
        [-0.0425,  0.4129,  0.1824,  0.3168,  0.0989, -0.1702, -0.0621,  0.3151,
         -0.1726,  0.2237]], grad_fn=<AddmmBackward>)

In [21]:
softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)
pred_probab

tensor([[0.0747, 0.1346, 0.1167, 0.1238, 0.0978, 0.0730, 0.0791, 0.1204, 0.0781,
         0.1019],
        [0.0734, 0.1461, 0.1109, 0.1217, 0.0963, 0.0696, 0.0775, 0.1237, 0.0712,
         0.1096],
        [0.0841, 0.1327, 0.1053, 0.1205, 0.0969, 0.0740, 0.0825, 0.1203, 0.0739,
         0.1098]], grad_fn=<SoftmaxBackward>)

In [22]:
print("Model structure: ", model, "\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Model structure:  NeuralNetwork(
  (flatten): Flatten()
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
) 


Layer: linear_relu_stack.0.weight | Size: torch.Size([512, 784]) | Values : tensor([[ 0.0135, -0.0254, -0.0342,  ...,  0.0179,  0.0152, -0.0279],
        [-0.0004, -0.0217, -0.0089,  ...,  0.0090, -0.0156, -0.0202]],
       device='cuda:0', grad_fn=<SliceBackward>) 

Layer: linear_relu_stack.0.bias | Size: torch.Size([512]) | Values : tensor([-0.0269,  0.0312], device='cuda:0', grad_fn=<SliceBackward>) 

Layer: linear_relu_stack.2.weight | Size: torch.Size([512, 512]) | Values : tensor([[-0.0236, -0.0054, -0.0365,  ..., -0.0162,  0.0290, -0.0231],
        [ 0.0050, -0.0391,  0.0083,  ...,  0.0302, -0.0248, -0.0208]],
       device='cuda:0', grad_fn=<SliceBackward>) 

Layer: 